version: "3.7"

services:
  superset:
    image: apache/superset:2.1.0
    container_name: superset_app
    restart: unless-stopped
    ports:
      - "8088:8088"
    environment:
      SUPERSET_ENV: production
      SUPERSET_SECRET_KEY: "iOUaWl9W5gk+U+gQmsRpZMbxyK5ME+jB6v5Eb3JkWyA="
      SUPERSET_LOG_LEVEL: info
    volumes:
      - superset_home:/app/superset_home
    depends_on:
      - superset_db
      - superset_redis

  superset_db:
    image: postgres:16
    container_name: superset_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: superset
      POSTGRES_USER: superset
      POSTGRES_PASSWORD: superset
    volumes:
      - superset_db_home:/var/lib/postgresql/data

  superset_redis:
    image: redis:7
    container_name: superset_redis
    restart: unless-stopped
    volumes:
      - superset_redis:/data

  superset_worker:
    image: apache/superset:2.1.0
    container_name: superset_worker
    command: ["celery", "--app=superset.tasks.celery_app:app", "worker", "--pool=prefork", "-O", "fair", "-c", "4"]
    depends_on:
      - superset
      - superset_redis
    environment:
      SUPERSET_ENV: production
      SUPERSET_SECRET_KEY: "iOUaWl9W5gk+U+gQmsRpZMbxyK5ME+jB6v5Eb3JkWyA="
    volumes:
      - superset_home:/app/superset_home

  superset_beat:
    image: apache/superset:2.1.0
    container_name: superset_beat
    command: ["celery", "--app=superset.tasks.celery_app:app", "beat", "-l", "info"]
    depends_on:
      - superset_worker
    environment:
      SUPERSET_ENV: production
      SUPERSET_SECRET_KEY: "iOUaWl9W5gk+U+gQmsRpZMbxyK5ME+jB6v5Eb3JkWyA="
    volumes:
      - superset_home:/app/superset_home

  superset_init:
    image: apache/superset:2.1.0
    container_name: superset_init
    depends_on:
      - superset_db
      - superset_redis
    entrypoint: >
      /bin/bash -c "
      superset db upgrade &&
      superset init
      "
    environment:
      SUPERSET_ENV: production
      SUPERSET_SECRET_KEY: "iOUaWl9W5gk+U+gQmsRpZMbxyK5ME+jB6v5Eb3JkWyA="
    volumes:
      - superset_home:/app/superset_home

volumes:
  superset_db_home:
    external: true
  superset_redis:
    external: true
  superset_home:
    external: true
